(* TODO: [ERR] consider better error handling *)

[@@@warning "-44"]
(* case 1: [open Cmdliner] shadows [ Arg ] which is fine because we use it multiple times for this cli setup *)

module A = Cmdliner.Arg

(*  TODO: [TEST] add parameterised tests for this, positive and negative tests *)

(** RFC 1123 hostname pattern in POSIX ERE syntax -- generated by a bot. *)
let hostname_regex =
  Re.Posix.compile_pat
    {|^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.?$|}

let validate_hostname h =
  if String.length h = 0 then Error (`Msg "Bind address cannot be empty")
  else if String.length h > 255 then
    Error (`Msg "Bind address too long (max 255 characters)")
  else if Re.execp hostname_regex h then Ok h
  else Error (`Msg "Invalid hostname format (abide by RFC 1123)")

let validate_ipv4 s =
  try
    let _ = Unix.inet_addr_of_string s in
    Ok s
  with _ -> Error (`Msg "Invalid IPv4 address")

let host_or_ipv4_addr_conv =
  let validate s =
    match validate_ipv4 s with
    | Ok _ as ok -> ok
    | Error _ -> validate_hostname s
  in
  let print fmt s = Format.fprintf fmt "%s" s in
  A.conv (validate, print)

let validate_port p =
  if p < 1 || p > 65535 then Error "Port must be between 1 and 65535"
  else if p < 1024 && Unix.getuid () <> 0 then
    Error "Ports <1024 are privileged; run as root or choose >=1024"
  else Ok p

let port_conv =
  let parse s =
    try
      s |> int_of_string |> validate_port
      |> Result.map_error (fun msg -> `Msg msg)
    with Failure _ -> Error (`Msg "Port must be an integer")
  in
  let print fmt p = Format.fprintf fmt "%d" p in
  A.conv (parse, print)

let timeout_arg =
  let default = 30 in
  let doc =
    "Connection timeout in seconds (default: " ^ Int.to_string default ^ ")"
  in
  A.(value & opt int 30 & info [ "timeout" ] ~docv:"SECONDS" ~doc)

let log_level_arg =
  let open Logs in
  let levels =
    [ Debug; Info; Warning; Error ]
    |> List.map (fun level -> (Some level |> level_to_string, level))
  in
  let default_level = Info in
  let levels_str = levels |> List.map fst |> String.concat ", " in
  let default_str = Some default_level |> level_to_string in
  let doc =
    Printf.sprintf "Logging level: %s (default: %s)" levels_str default_str
  in
  A.(
    value
    & opt (enum levels) default_level
    & info [ "log-level" ] ~docv:"LEVEL" ~doc)
[@@warning "-45-44"]

let port_server_arg =
  let default = 4242 in
  let doc =
    "Server port to listen on (default " ^ Int.to_string default ^ ")"
  in
  A.(value & opt port_conv default & info [ "port"; "p" ] ~docv:"PORT" ~doc)

let bind_arg =
  let default = "localhost" in
  let doc = "Bind address (IPv4 addr or hostname, default: " ^ default ^ ")" in
  A.(
    value
    & opt host_or_ipv4_addr_conv default
    & info [ "bind" ] ~docv:"ADDR" ~doc)

let port_client_arg =
  let default = 4242 in
  let doc =
    "Server port to connect to (default: " ^ Int.to_string default ^ ")"
  in
  A.(value & opt port_conv default & info [ "port"; "p" ] ~docv:"PORT" ~doc)

let host_arg =
  let default = "localhost" in
  let doc = "Server hostname or IP (default: " ^ default ^ ")" in
  A.(
    value
    & opt host_or_ipv4_addr_conv default
    & info [ "host" ] ~docv:"HOST" ~doc)

let run_server port bind timeout log_level =
  let terminal = Server.make_terminal_config ~log_level () in
  let net = Server.{ bind; timeout; port } in
  try Lwt_main.run (Server.run ~terminal ~net ())
  with e ->
    Lwt_io.eprintf "Fatal server error: %s\n%!" (Printexc.to_string e)
    |> Lwt_main.run;
    exit 1

let run_client host port timeout log_level =
  let terminal = Client.make_terminal_config ~log_level () in
  let net = Client.{ host; timeout; port } in
  try Lwt_main.run (Client.run ~terminal ~net ())
  with e ->
    Lwt_io.eprintf "Fatal client error: %s\n%!" (Printexc.to_string e)
    |> Lwt_main.run;
    exit 1

let cmd =
  let open Cmdliner in
  Cmd.group
    (Cmd.info "chat" ~version:"0.1.0" ~doc:"Simple one-on-one chat application")
    [
      Cmd.make
        (Cmd.info "server" ~doc:"Start a chat server")
        Term.(
          const run_server $ port_server_arg $ bind_arg $ timeout_arg
          $ log_level_arg);
      Cmd.make
        (Cmd.info "client" ~doc:"Connect to a chat server")
        Term.(
          const run_client $ host_arg $ port_client_arg $ timeout_arg
          $ log_level_arg);
    ]

let run () = exit (Cmdliner.Cmd.eval cmd)
