open Chat
open Input_types
module F = Frame
module FR = Frame_reader
module TH = Test_helpers

(** A torture payload: 1. "Fireball" written in multiple languages 2. UTF-8
    multibyte sequences 3. RTL scripts 4. CJK 5. emoji surrogate ranges 6.
    embedded NUL 7. raw high bytes (0xFF, 0xFE) 8. mixed-width codepoints

    NOTE: [AI-usage]: used random chatbot to generate this *)
let byte_agnostic_torture_string =
  "🔥fireball🔥\x00火球كرة_ناريةכדור_אשファイアボールลูกไฟогненный_шарπύρινη_σφαίρα\xFF\xFE🧙🔥💥"

(** NOTE:[AI-usage] these were generated by a chatbot (model:Anthropic's Haiku
    4.5). *)
let legal_payloads =
  [
    (* Basic cases *)
    { desc = "ASCII text"; bytes = Bytes.of_string "hello world"; err = None };
    { desc = "Empty"; bytes = Bytes.empty; err = None };
    (* UTF-8 and internationalization *)
    {
      desc = "Emoji (UTF-8)";
      bytes = Bytes.of_string "Hello 👋 World 🚀";
      err = None;
    };
    { desc = "Mandarin"; bytes = Bytes.of_string "你好世界"; err = None };
    { desc = "Arabic"; bytes = Bytes.of_string "مرحبا بالعالم"; err = None };
    { desc = "Hebrew"; bytes = Bytes.of_string "שלום עולם"; err = None };
    { desc = "Japanese"; bytes = Bytes.of_string "こんにちは世界"; err = None };
    { desc = "Thai"; bytes = Bytes.of_string "สวัสดีชาวโลก"; err = None };
    { desc = "Russian"; bytes = Bytes.of_string "Привет мир"; err = None };
    { desc = "Greek"; bytes = Bytes.of_string "Γεια σας κόσμε"; err = None };
    (* Binary and control *)
    { desc = "Null bytes"; bytes = Bytes.of_string "\x00\x00\x00"; err = None };
    { desc = "Single null"; bytes = Bytes.of_string "\x00"; err = None };
    {
      desc = "High bytes";
      bytes = Bytes.of_string "\xFF\xFE\xFD\xFC";
      err = None;
    };
    { desc = "All high (0xFF)"; bytes = Bytes.make 10 '\xFF'; err = None };
    { desc = "All low (0x00)"; bytes = Bytes.make 10 '\x00'; err = None };
    (* Terminal and control codes *)
    {
      desc = "ANSI color codes";
      bytes = Bytes.of_string "\x1B[31mRed\x1B[0m";
      err = None;
    };
    { desc = "Bell character"; bytes = Bytes.of_string "\x07"; err = None };
    { desc = "Bell + Escape"; bytes = Bytes.of_string "\x07\x1B"; err = None };
    {
      desc = "Control chars (0x00-0x09)";
      bytes = Bytes.of_string "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09";
      err = None;
    };
    {
      desc = "Newlines";
      bytes = Bytes.of_string "line1\nline2\nline3";
      err = None;
    };
    { desc = "Tabs"; bytes = Bytes.of_string "col1\tcol2\tcol3"; err = None };
    {
      desc = "Windows CRLF";
      bytes = Bytes.of_string "line1\r\nline2\r\nline3";
      err = None;
    };
    (* Mixed *)
    {
      desc = "UTF-8 + nulls";
      bytes = Bytes.of_string "Hello\x00👋\x00World";
      err = None;
    };
    {
      desc = "UTF-8 + high bytes";
      bytes = Bytes.of_string "Hello\xFF👋\xFEWorld";
      err = None;
    };
    {
      desc = "Emoji + nulls + high";
      bytes = Bytes.of_string "🎉\x00\xFF🎊";
      err = None;
    };
    {
      desc = "Binary blob";
      bytes = Bytes.of_string "\xDE\xAD\xBE\xEF\xCA\xFE";
      err = None;
    };
    (* Emoji *)
    { desc = "Emoji only"; bytes = Bytes.of_string "😀😁😂😃😄😅"; err = None };
    { desc = "Mixed emojis"; bytes = Bytes.of_string "👋🌍🚀💻🎉"; err = None };
    (* Edge cases *)
    {
      desc = "Max payload (1MB)";
      bytes = Bytes.make Frame.max_payload_size 'x';
      err = None;
    };
    {
      desc = "Torture: all the types in one string";
      bytes = Bytes.of_string byte_agnostic_torture_string;
      err = None;
    };
  ]

let illegal_serialised_frames =
  [
    {
      desc = "Payload too big (>1MB)";
      bytes =
        Test_helpers.make_raw_frame_bs 0 1l
          (Bytes.make (1 + Frame.max_payload_size) 'x');
      err =
        Frame.Payload_too_big
          { sz = 1 + Frame.max_payload_size; max = Frame.max_payload_size };
    };
    {
      desc = "Payload too small";
      bytes = Bytes.empty;
      err = Frame.Header_too_short;
    };
    {
      desc = "Unknown frame type";
      bytes =
        Test_helpers.make_raw_frame_bs 12 (Int32.of_int 12)
          (Bytes.of_string "hello world");
      err = Frame.Unknown_frame_type 12;
    };
    {
      desc = "Payload shorter than header's claim";
      bytes =
        (let complete_bs = 'x' |> String.make 10 |> TH.msg |> Frame.to_bytes in
         let partial_bs = Bytes.create 10 in
         Bytes.blit complete_bs 0 partial_bs 0 10;
         partial_bs);
      err = Frame.Payload_too_short;
    };
  ]
